# Generated by Django 4.1 on 2024-04-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_usermaterial_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
